<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;
use App\Models\Nationality;

class NationalitySeeder extends Seeder
{
    public function run(): void
    {
        $nationalities = [
            ['name' => 'Aruba', 'iso_code' => 'ABW', 'country' => 'Aruba', 'is_default' => false],
            ['name' => 'Afghanistan', 'iso_code' => 'AFG', 'country' => 'Afghanistan', 'is_default' => false],
            ['name' => 'Angola', 'iso_code' => 'AGO', 'country' => 'Angola', 'is_default' => false],
            ['name' => 'Anguilla', 'iso_code' => 'AIA', 'country' => 'Anguilla', 'is_default' => false],
            ['name' => 'Åland Islands', 'iso_code' => 'ALA', 'country' => 'Åland Islands', 'is_default' => false],
            ['name' => 'Albania', 'iso_code' => 'ALB', 'country' => 'Albania', 'is_default' => false],
            ['name' => 'Andorra', 'iso_code' => 'AND', 'country' => 'Andorra', 'is_default' => false],
            ['name' => 'United Arab Emirates', 'iso_code' => 'ARE', 'country' => 'United Arab Emirates', 'is_default' => false],
            ['name' => 'Argentina', 'iso_code' => 'ARG', 'country' => 'Argentina', 'is_default' => true],
            ['name' => 'Armenia', 'iso_code' => 'ARM', 'country' => 'Armenia', 'is_default' => false],
            ['name' => 'American Samoa', 'iso_code' => 'ASM', 'country' => 'American Samoa', 'is_default' => false],
            ['name' => 'Antarctica', 'iso_code' => 'ATA', 'country' => 'Antarctica', 'is_default' => false],
            ['name' => 'French Southern Territories', 'iso_code' => 'ATF', 'country' => 'French Southern Territories', 'is_default' => false],
            ['name' => 'Antigua and Barbuda', 'iso_code' => 'ATG', 'country' => 'Antigua and Barbuda', 'is_default' => false],
            ['name' => 'Australia', 'iso_code' => 'AUS', 'country' => 'Australia', 'is_default' => false],
            ['name' => 'Austria', 'iso_code' => 'AUT', 'country' => 'Austria', 'is_default' => false],
            ['name' => 'Azerbaijan', 'iso_code' => 'AZE', 'country' => 'Azerbaijan', 'is_default' => false],
            ['name' => 'Burundi', 'iso_code' => 'BDI', 'country' => 'Burundi', 'is_default' => false],
            ['name' => 'Belgium', 'iso_code' => 'BEL', 'country' => 'Belgium', 'is_default' => false],
            ['name' => 'Benin', 'iso_code' => 'BEN', 'country' => 'Benin', 'is_default' => false],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'iso_code' => 'BES', 'country' => 'Bonaire, Sint Eustatius and Saba', 'is_default' => false],
            ['name' => 'Burkina Faso', 'iso_code' => 'BFA', 'country' => 'Burkina Faso', 'is_default' => false],
            ['name' => 'Bangladesh', 'iso_code' => 'BGD', 'country' => 'Bangladesh', 'is_default' => false],
            ['name' => 'Bulgaria', 'iso_code' => 'BGR', 'country' => 'Bulgaria', 'is_default' => false],
            ['name' => 'Bahrain', 'iso_code' => 'BHR', 'country' => 'Bahrain', 'is_default' => false],
            ['name' => 'Bahamas', 'iso_code' => 'BHS', 'country' => 'Bahamas', 'is_default' => false],
            ['name' => 'Bosnia and Herzegovina', 'iso_code' => 'BIH', 'country' => 'Bosnia and Herzegovina', 'is_default' => false],
            ['name' => 'Saint Barthélemy', 'iso_code' => 'BLM', 'country' => 'Saint Barthélemy', 'is_default' => false],
            ['name' => 'Belarus', 'iso_code' => 'BLR', 'country' => 'Belarus', 'is_default' => false],
            ['name' => 'Belize', 'iso_code' => 'BLZ', 'country' => 'Belize', 'is_default' => false],
            ['name' => 'Bermuda', 'iso_code' => 'BMU', 'country' => 'Bermuda', 'is_default' => false],
            ['name' => 'Bolivia, Plurinational State of', 'iso_code' => 'BOL', 'country' => 'Bolivia, Plurinational State of', 'is_default' => false],
            ['name' => 'Brazil', 'iso_code' => 'BRA', 'country' => 'Brazil', 'is_default' => false],
            ['name' => 'Barbados', 'iso_code' => 'BRB', 'country' => 'Barbados', 'is_default' => false],
            ['name' => 'Brunei Darussalam', 'iso_code' => 'BRN', 'country' => 'Brunei Darussalam', 'is_default' => false],
            ['name' => 'Bhutan', 'iso_code' => 'BTN', 'country' => 'Bhutan', 'is_default' => false],
            ['name' => 'Bouvet Island', 'iso_code' => 'BVT', 'country' => 'Bouvet Island', 'is_default' => false],
            ['name' => 'Botswana', 'iso_code' => 'BWA', 'country' => 'Botswana', 'is_default' => false],
            ['name' => 'Central African Republic', 'iso_code' => 'CAF', 'country' => 'Central African Republic', 'is_default' => false],
            ['name' => 'Canada', 'iso_code' => 'CAN', 'country' => 'Canada', 'is_default' => false],
            ['name' => 'Cocos (Keeling) Islands', 'iso_code' => 'CCK', 'country' => 'Cocos (Keeling) Islands', 'is_default' => false],
            ['name' => 'Switzerland', 'iso_code' => 'CHE', 'country' => 'Switzerland', 'is_default' => false],
            ['name' => 'Chile', 'iso_code' => 'CHL', 'country' => 'Chile', 'is_default' => false],
            ['name' => 'China', 'iso_code' => 'CHN', 'country' => 'China', 'is_default' => false],
            ['name' => 'Côte d\'Ivoire', 'iso_code' => 'CIV', 'country' => 'Côte d\'Ivoire', 'is_default' => false],
            ['name' => 'Cameroon', 'iso_code' => 'CMR', 'country' => 'Cameroon', 'is_default' => false],
            ['name' => 'Congo, The Democratic Republic of the', 'iso_code' => 'COD', 'country' => 'Congo, The Democratic Republic of the', 'is_default' => false],
            ['name' => 'Congo', 'iso_code' => 'COG', 'country' => 'Congo', 'is_default' => false],
            ['name' => 'Cook Islands', 'iso_code' => 'COK', 'country' => 'Cook Islands', 'is_default' => false],
            ['name' => 'Colombia', 'iso_code' => 'COL', 'country' => 'Colombia', 'is_default' => false],
            ['name' => 'Comoros', 'iso_code' => 'COM', 'country' => 'Comoros', 'is_default' => false],
            ['name' => 'Cabo Verde', 'iso_code' => 'CPV', 'country' => 'Cabo Verde', 'is_default' => false],
            ['name' => 'Costa Rica', 'iso_code' => 'CRI', 'country' => 'Costa Rica', 'is_default' => false],
            ['name' => 'Cuba', 'iso_code' => 'CUB', 'country' => 'Cuba', 'is_default' => false],
            ['name' => 'Curaçao', 'iso_code' => 'CUW', 'country' => 'Curaçao', 'is_default' => false],
            ['name' => 'Christmas Island', 'iso_code' => 'CXR', 'country' => 'Christmas Island', 'is_default' => false],
            ['name' => 'Cayman Islands', 'iso_code' => 'CYM', 'country' => 'Cayman Islands', 'is_default' => false],
            ['name' => 'Cyprus', 'iso_code' => 'CYP', 'country' => 'Cyprus', 'is_default' => false],
            ['name' => 'Czechia', 'iso_code' => 'CZE', 'country' => 'Czechia', 'is_default' => false],
            ['name' => 'Germany', 'iso_code' => 'DEU', 'country' => 'Germany', 'is_default' => false],
            ['name' => 'Djibouti', 'iso_code' => 'DJI', 'country' => 'Djibouti', 'is_default' => false],
            ['name' => 'Dominica', 'iso_code' => 'DMA', 'country' => 'Dominica', 'is_default' => false],
            ['name' => 'Denmark', 'iso_code' => 'DNK', 'country' => 'Denmark', 'is_default' => false],
            ['name' => 'Dominican Republic', 'iso_code' => 'DOM', 'country' => 'Dominican Republic', 'is_default' => false],
            ['name' => 'Algeria', 'iso_code' => 'DZA', 'country' => 'Algeria', 'is_default' => false],
            ['name' => 'Ecuador', 'iso_code' => 'ECU', 'country' => 'Ecuador', 'is_default' => false],
            ['name' => 'Egypt', 'iso_code' => 'EGY', 'country' => 'Egypt', 'is_default' => false],
            ['name' => 'Eritrea', 'iso_code' => 'ERI', 'country' => 'Eritrea', 'is_default' => false],
            ['name' => 'Western Sahara', 'iso_code' => 'ESH', 'country' => 'Western Sahara', 'is_default' => false],
            ['name' => 'Spain', 'iso_code' => 'ESP', 'country' => 'Spain', 'is_default' => false],
            ['name' => 'Estonia', 'iso_code' => 'EST', 'country' => 'Estonia', 'is_default' => false],
            ['name' => 'Ethiopia', 'iso_code' => 'ETH', 'country' => 'Ethiopia', 'is_default' => false],
            ['name' => 'Finland', 'iso_code' => 'FIN', 'country' => 'Finland', 'is_default' => false],
            ['name' => 'Fiji', 'iso_code' => 'FJI', 'country' => 'Fiji', 'is_default' => false],
            ['name' => 'Falkland Islands (Malvinas)', 'iso_code' => 'FLK', 'country' => 'Falkland Islands (Malvinas)', 'is_default' => false],
            ['name' => 'France', 'iso_code' => 'FRA', 'country' => 'France', 'is_default' => false],
            ['name' => 'Faroe Islands', 'iso_code' => 'FRO', 'country' => 'Faroe Islands', 'is_default' => false],
            ['name' => 'Micronesia, Federated States of', 'iso_code' => 'FSM', 'country' => 'Micronesia, Federated States of', 'is_default' => false],
            ['name' => 'Gabon', 'iso_code' => 'GAB', 'country' => 'Gabon', 'is_default' => false],
            ['name' => 'United Kingdom', 'iso_code' => 'GBR', 'country' => 'United Kingdom', 'is_default' => false],
            ['name' => 'Georgia', 'iso_code' => 'GEO', 'country' => 'Georgia', 'is_default' => false],
            ['name' => 'Guernsey', 'iso_code' => 'GGY', 'country' => 'Guernsey', 'is_default' => false],
            ['name' => 'Ghana', 'iso_code' => 'GHA', 'country' => 'Ghana', 'is_default' => false],
            ['name' => 'Gibraltar', 'iso_code' => 'GIB', 'country' => 'Gibraltar', 'is_default' => false],
            ['name' => 'Guinea', 'iso_code' => 'GIN', 'country' => 'Guinea', 'is_default' => false],
            ['name' => 'Guadeloupe', 'iso_code' => 'GLP', 'country' => 'Guadeloupe', 'is_default' => false],
            ['name' => 'Gambia', 'iso_code' => 'GMB', 'country' => 'Gambia', 'is_default' => false],
            ['name' => 'Guinea-Bissau', 'iso_code' => 'GNB', 'country' => 'Guinea-Bissau', 'is_default' => false],
            ['name' => 'Equatorial Guinea', 'iso_code' => 'GNQ', 'country' => 'Equatorial Guinea', 'is_default' => false],
            ['name' => 'Greece', 'iso_code' => 'GRC', 'country' => 'Greece', 'is_default' => false],
            ['name' => 'Grenada', 'iso_code' => 'GRD', 'country' => 'Grenada', 'is_default' => false],
            ['name' => 'Greenland', 'iso_code' => 'GRL', 'country' => 'Greenland', 'is_default' => false],
            ['name' => 'Guatemala', 'iso_code' => 'GTM', 'country' => 'Guatemala', 'is_default' => false],
            ['name' => 'French Guiana', 'iso_code' => 'GUF', 'country' => 'French Guiana', 'is_default' => false],
            ['name' => 'Guam', 'iso_code' => 'GUM', 'country' => 'Guam', 'is_default' => false],
            ['name' => 'Guyana', 'iso_code' => 'GUY', 'country' => 'Guyana', 'is_default' => false],
            ['name' => 'Hong Kong', 'iso_code' => 'HKG', 'country' => 'Hong Kong', 'is_default' => false],
            ['name' => 'Heard Island and McDonald Islands', 'iso_code' => 'HMD', 'country' => 'Heard Island and McDonald Islands', 'is_default' => false],
            ['name' => 'Honduras', 'iso_code' => 'HND', 'country' => 'Honduras', 'is_default' => false],
            ['name' => 'Croatia', 'iso_code' => 'HRV', 'country' => 'Croatia', 'is_default' => false],
            ['name' => 'Haiti', 'iso_code' => 'HTI', 'country' => 'Haiti', 'is_default' => false],
            ['name' => 'Hungary', 'iso_code' => 'HUN', 'country' => 'Hungary', 'is_default' => false],
            ['name' => 'Indonesia', 'iso_code' => 'IDN', 'country' => 'Indonesia', 'is_default' => false],
            ['name' => 'Isle of Man', 'iso_code' => 'IMN', 'country' => 'Isle of Man', 'is_default' => false],
            ['name' => 'India', 'iso_code' => 'IND', 'country' => 'India', 'is_default' => false],
            ['name' => 'British Indian Ocean Territory', 'iso_code' => 'IOT', 'country' => 'British Indian Ocean Territory', 'is_default' => false],
            ['name' => 'Ireland', 'iso_code' => 'IRL', 'country' => 'Ireland', 'is_default' => false],
            ['name' => 'Iran, Islamic Republic of', 'iso_code' => 'IRN', 'country' => 'Iran, Islamic Republic of', 'is_default' => false],
            ['name' => 'Iraq', 'iso_code' => 'IRQ', 'country' => 'Iraq', 'is_default' => false],
            ['name' => 'Iceland', 'iso_code' => 'ISL', 'country' => 'Iceland', 'is_default' => false],
            ['name' => 'Israel', 'iso_code' => 'ISR', 'country' => 'Israel', 'is_default' => false],
            ['name' => 'Italy', 'iso_code' => 'ITA', 'country' => 'Italy', 'is_default' => false],
            ['name' => 'Jamaica', 'iso_code' => 'JAM', 'country' => 'Jamaica', 'is_default' => false],
            ['name' => 'Jersey', 'iso_code' => 'JEY', 'country' => 'Jersey', 'is_default' => false],
            ['name' => 'Jordan', 'iso_code' => 'JOR', 'country' => 'Jordan', 'is_default' => false],
            ['name' => 'Japan', 'iso_code' => 'JPN', 'country' => 'Japan', 'is_default' => false],
            ['name' => 'Kazakhstan', 'iso_code' => 'KAZ', 'country' => 'Kazakhstan', 'is_default' => false],
            ['name' => 'Kenya', 'iso_code' => 'KEN', 'country' => 'Kenya', 'is_default' => false],
            ['name' => 'Kyrgyzstan', 'iso_code' => 'KGZ', 'country' => 'Kyrgyzstan', 'is_default' => false],
            ['name' => 'Cambodia', 'iso_code' => 'KHM', 'country' => 'Cambodia', 'is_default' => false],
            ['name' => 'Kiribati', 'iso_code' => 'KIR', 'country' => 'Kiribati', 'is_default' => false],
            ['name' => 'Saint Kitts and Nevis', 'iso_code' => 'KNA', 'country' => 'Saint Kitts and Nevis', 'is_default' => false],
            ['name' => 'Korea, Republic of', 'iso_code' => 'KOR', 'country' => 'Korea, Republic of', 'is_default' => false],
            ['name' => 'Kuwait', 'iso_code' => 'KWT', 'country' => 'Kuwait', 'is_default' => false],
            ['name' => 'Lao People\'s Democratic Republic', 'iso_code' => 'LAO', 'country' => 'Lao People\'s Democratic Republic', 'is_default' => false],
            ['name' => 'Lebanon', 'iso_code' => 'LBN', 'country' => 'Lebanon', 'is_default' => false],
            ['name' => 'Liberia', 'iso_code' => 'LBR', 'country' => 'Liberia', 'is_default' => false],
            ['name' => 'Libya', 'iso_code' => 'LBY', 'country' => 'Libya', 'is_default' => false],
            ['name' => 'Saint Lucia', 'iso_code' => 'LCA', 'country' => 'Saint Lucia', 'is_default' => false],
            ['name' => 'Liechtenstein', 'iso_code' => 'LIE', 'country' => 'Liechtenstein', 'is_default' => false],
            ['name' => 'Sri Lanka', 'iso_code' => 'LKA', 'country' => 'Sri Lanka', 'is_default' => false],
            ['name' => 'Lesotho', 'iso_code' => 'LSO', 'country' => 'Lesotho', 'is_default' => false],
            ['name' => 'Lithuania', 'iso_code' => 'LTU', 'country' => 'Lithuania', 'is_default' => false],
            ['name' => 'Luxembourg', 'iso_code' => 'LUX', 'country' => 'Luxembourg', 'is_default' => false],
            ['name' => 'Latvia', 'iso_code' => 'LVA', 'country' => 'Latvia', 'is_default' => false],
            ['name' => 'Macao', 'iso_code' => 'MAC', 'country' => 'Macao', 'is_default' => false],
            ['name' => 'Saint Martin (French part)', 'iso_code' => 'MAF', 'country' => 'Saint Martin (French part)', 'is_default' => false],
            ['name' => 'Morocco', 'iso_code' => 'MAR', 'country' => 'Morocco', 'is_default' => false],
            ['name' => 'Monaco', 'iso_code' => 'MCO', 'country' => 'Monaco', 'is_default' => false],
            ['name' => 'Moldova, Republic of', 'iso_code' => 'MDA', 'country' => 'Moldova, Republic of', 'is_default' => false],
            ['name' => 'Madagascar', 'iso_code' => 'MDG', 'country' => 'Madagascar', 'is_default' => false],
            ['name' => 'Maldives', 'iso_code' => 'MDV', 'country' => 'Maldives', 'is_default' => false],
            ['name' => 'Mexico', 'iso_code' => 'MEX', 'country' => 'Mexico', 'is_default' => false],
            ['name' => 'Marshall Islands', 'iso_code' => 'MHL', 'country' => 'Marshall Islands', 'is_default' => false],
            ['name' => 'North Macedonia', 'iso_code' => 'MKD', 'country' => 'North Macedonia', 'is_default' => false],
            ['name' => 'Mali', 'iso_code' => 'MLI', 'country' => 'Mali', 'is_default' => false],
            ['name' => 'Malta', 'iso_code' => 'MLT', 'country' => 'Malta', 'is_default' => false],
            ['name' => 'Myanmar', 'iso_code' => 'MMR', 'country' => 'Myanmar', 'is_default' => false],
            ['name' => 'Montenegro', 'iso_code' => 'MNE', 'country' => 'Montenegro', 'is_default' => false],
            ['name' => 'Mongolia', 'iso_code' => 'MNG', 'country' => 'Mongolia', 'is_default' => false],
            ['name' => 'Northern Mariana Islands', 'iso_code' => 'MNP', 'country' => 'Northern Mariana Islands', 'is_default' => false],
            ['name' => 'Mozambique', 'iso_code' => 'MOZ', 'country' => 'Mozambique', 'is_default' => false],
            ['name' => 'Mauritania', 'iso_code' => 'MRT', 'country' => 'Mauritania', 'is_default' => false],
            ['name' => 'Montserrat', 'iso_code' => 'MSR', 'country' => 'Montserrat', 'is_default' => false],
            ['name' => 'Martinique', 'iso_code' => 'MTQ', 'country' => 'Martinique', 'is_default' => false],
            ['name' => 'Mauritius', 'iso_code' => 'MUS', 'country' => 'Mauritius', 'is_default' => false],
            ['name' => 'Malawi', 'iso_code' => 'MWI', 'country' => 'Malawi', 'is_default' => false],
            ['name' => 'Malaysia', 'iso_code' => 'MYS', 'country' => 'Malaysia', 'is_default' => false],
            ['name' => 'Mayotte', 'iso_code' => 'MYT', 'country' => 'Mayotte', 'is_default' => false],
            ['name' => 'Namibia', 'iso_code' => 'NAM', 'country' => 'Namibia', 'is_default' => false],
            ['name' => 'New Caledonia', 'iso_code' => 'NCL', 'country' => 'New Caledonia', 'is_default' => false],
            ['name' => 'Niger', 'iso_code' => 'NER', 'country' => 'Niger', 'is_default' => false],
            ['name' => 'Norfolk Island', 'iso_code' => 'NFK', 'country' => 'Norfolk Island', 'is_default' => false],
            ['name' => 'Nigeria', 'iso_code' => 'NGA', 'country' => 'Nigeria', 'is_default' => false],
            ['name' => 'Nicaragua', 'iso_code' => 'NIC', 'country' => 'Nicaragua', 'is_default' => false],
            ['name' => 'Niue', 'iso_code' => 'NIU', 'country' => 'Niue', 'is_default' => false],
            ['name' => 'Netherlands', 'iso_code' => 'NLD', 'country' => 'Netherlands', 'is_default' => false],
            ['name' => 'Norway', 'iso_code' => 'NOR', 'country' => 'Norway', 'is_default' => false],
            ['name' => 'Nepal', 'iso_code' => 'NPL', 'country' => 'Nepal', 'is_default' => false],
            ['name' => 'Nauru', 'iso_code' => 'NRU', 'country' => 'Nauru', 'is_default' => false],
            ['name' => 'New Zealand', 'iso_code' => 'NZL', 'country' => 'New Zealand', 'is_default' => false],
            ['name' => 'Oman', 'iso_code' => 'OMN', 'country' => 'Oman', 'is_default' => false],
            ['name' => 'Pakistan', 'iso_code' => 'PAK', 'country' => 'Pakistan', 'is_default' => false],
            ['name' => 'Panama', 'iso_code' => 'PAN', 'country' => 'Panama', 'is_default' => false],
            ['name' => 'Pitcairn', 'iso_code' => 'PCN', 'country' => 'Pitcairn', 'is_default' => false],
            ['name' => 'Peru', 'iso_code' => 'PER', 'country' => 'Peru', 'is_default' => false],
            ['name' => 'Philippines', 'iso_code' => 'PHL', 'country' => 'Philippines', 'is_default' => false],
            ['name' => 'Palau', 'iso_code' => 'PLW', 'country' => 'Palau', 'is_default' => false],
            ['name' => 'Papua New Guinea', 'iso_code' => 'PNG', 'country' => 'Papua New Guinea', 'is_default' => false],
            ['name' => 'Poland', 'iso_code' => 'POL', 'country' => 'Poland', 'is_default' => false],
            ['name' => 'Puerto Rico', 'iso_code' => 'PRI', 'country' => 'Puerto Rico', 'is_default' => false],
            ['name' => 'Korea, Democratic People\'s Republic of', 'iso_code' => 'PRK', 'country' => 'Korea, Democratic People\'s Republic of', 'is_default' => false],
            ['name' => 'Portugal', 'iso_code' => 'PRT', 'country' => 'Portugal', 'is_default' => false],
            ['name' => 'Paraguay', 'iso_code' => 'PRY', 'country' => 'Paraguay', 'is_default' => false],
            ['name' => 'Palestine, State of', 'iso_code' => 'PSE', 'country' => 'Palestine, State of', 'is_default' => false],
            ['name' => 'French Polynesia', 'iso_code' => 'PYF', 'country' => 'French Polynesia', 'is_default' => false],
            ['name' => 'Qatar', 'iso_code' => 'QAT', 'country' => 'Qatar', 'is_default' => false],
            ['name' => 'Réunion', 'iso_code' => 'REU', 'country' => 'Réunion', 'is_default' => false],
            ['name' => 'Romania', 'iso_code' => 'ROU', 'country' => 'Romania', 'is_default' => false],
            ['name' => 'Russian Federation', 'iso_code' => 'RUS', 'country' => 'Russian Federation', 'is_default' => false],
            ['name' => 'Rwanda', 'iso_code' => 'RWA', 'country' => 'Rwanda', 'is_default' => false],
            ['name' => 'Saudi Arabia', 'iso_code' => 'SAU', 'country' => 'Saudi Arabia', 'is_default' => false],
            ['name' => 'Sudan', 'iso_code' => 'SDN', 'country' => 'Sudan', 'is_default' => false],
            ['name' => 'Senegal', 'iso_code' => 'SEN', 'country' => 'Senegal', 'is_default' => false],
            ['name' => 'Singapore', 'iso_code' => 'SGP', 'country' => 'Singapore', 'is_default' => false],
            ['name' => 'South Georgia and the South Sandwich Islands', 'iso_code' => 'SGS', 'country' => 'South Georgia and the South Sandwich Islands', 'is_default' => false],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'iso_code' => 'SHN', 'country' => 'Saint Helena, Ascension and Tristan da Cunha', 'is_default' => false],
            ['name' => 'Svalbard and Jan Mayen', 'iso_code' => 'SJM', 'country' => 'Svalbard and Jan Mayen', 'is_default' => false],
            ['name' => 'Solomon Islands', 'iso_code' => 'SLB', 'country' => 'Solomon Islands', 'is_default' => false],
            ['name' => 'Sierra Leone', 'iso_code' => 'SLE', 'country' => 'Sierra Leone', 'is_default' => false],
            ['name' => 'El Salvador', 'iso_code' => 'SLV', 'country' => 'El Salvador', 'is_default' => false],
            ['name' => 'San Marino', 'iso_code' => 'SMR', 'country' => 'San Marino', 'is_default' => false],
            ['name' => 'Somalia', 'iso_code' => 'SOM', 'country' => 'Somalia', 'is_default' => false],
            ['name' => 'Saint Pierre and Miquelon', 'iso_code' => 'SPM', 'country' => 'Saint Pierre and Miquelon', 'is_default' => false],
            ['name' => 'Serbia', 'iso_code' => 'SRB', 'country' => 'Serbia', 'is_default' => false],
            ['name' => 'South Sudan', 'iso_code' => 'SSD', 'country' => 'South Sudan', 'is_default' => false],
            ['name' => 'Sao Tome and Principe', 'iso_code' => 'STP', 'country' => 'Sao Tome and Principe', 'is_default' => false],
            ['name' => 'Suriname', 'iso_code' => 'SUR', 'country' => 'Suriname', 'is_default' => false],
            ['name' => 'Slovakia', 'iso_code' => 'SVK', 'country' => 'Slovakia', 'is_default' => false],
            ['name' => 'Slovenia', 'iso_code' => 'SVN', 'country' => 'Slovenia', 'is_default' => false],
            ['name' => 'Sweden', 'iso_code' => 'SWE', 'country' => 'Sweden', 'is_default' => false],
            ['name' => 'Eswatini', 'iso_code' => 'SWZ', 'country' => 'Eswatini', 'is_default' => false],
            ['name' => 'Sint Maarten (Dutch part)', 'iso_code' => 'SXM', 'country' => 'Sint Maarten (Dutch part)', 'is_default' => false],
            ['name' => 'Seychelles', 'iso_code' => 'SYC', 'country' => 'Seychelles', 'is_default' => false],
            ['name' => 'Syrian Arab Republic', 'iso_code' => 'SYR', 'country' => 'Syrian Arab Republic', 'is_default' => false],
            ['name' => 'Turks and Caicos Islands', 'iso_code' => 'TCA', 'country' => 'Turks and Caicos Islands', 'is_default' => false],
            ['name' => 'Chad', 'iso_code' => 'TCD', 'country' => 'Chad', 'is_default' => false],
            ['name' => 'Togo', 'iso_code' => 'TGO', 'country' => 'Togo', 'is_default' => false],
            ['name' => 'Thailand', 'iso_code' => 'THA', 'country' => 'Thailand', 'is_default' => false],
            ['name' => 'Tajikistan', 'iso_code' => 'TJK', 'country' => 'Tajikistan', 'is_default' => false],
            ['name' => 'Tokelau', 'iso_code' => 'TKL', 'country' => 'Tokelau', 'is_default' => false],
            ['name' => 'Turkmenistan', 'iso_code' => 'TKM', 'country' => 'Turkmenistan', 'is_default' => false],
            ['name' => 'Timor-Leste', 'iso_code' => 'TLS', 'country' => 'Timor-Leste', 'is_default' => false],
            ['name' => 'Tonga', 'iso_code' => 'TON', 'country' => 'Tonga', 'is_default' => false],
            ['name' => 'Trinidad and Tobago', 'iso_code' => 'TTO', 'country' => 'Trinidad and Tobago', 'is_default' => false],
            ['name' => 'Tunisia', 'iso_code' => 'TUN', 'country' => 'Tunisia', 'is_default' => false],
            ['name' => 'Turkey', 'iso_code' => 'TUR', 'country' => 'Turkey', 'is_default' => false],
            ['name' => 'Tuvalu', 'iso_code' => 'TUV', 'country' => 'Tuvalu', 'is_default' => false],
            ['name' => 'Taiwan, Province of China', 'iso_code' => 'TWN', 'country' => 'Taiwan, Province of China', 'is_default' => false],
            ['name' => 'Tanzania, United Republic of', 'iso_code' => 'TZA', 'country' => 'Tanzania, United Republic of', 'is_default' => false],
            ['name' => 'Uganda', 'iso_code' => 'UGA', 'country' => 'Uganda', 'is_default' => false],
            ['name' => 'Ukraine', 'iso_code' => 'UKR', 'country' => 'Ukraine', 'is_default' => false],
            ['name' => 'United States Minor Outlying Islands', 'iso_code' => 'UMI', 'country' => 'United States Minor Outlying Islands', 'is_default' => false],
            ['name' => 'Uruguay', 'iso_code' => 'URY', 'country' => 'Uruguay', 'is_default' => false],
            ['name' => 'United States', 'iso_code' => 'USA', 'country' => 'United States', 'is_default' => false],
            ['name' => 'Uzbekistan', 'iso_code' => 'UZB', 'country' => 'Uzbekistan', 'is_default' => false],
            ['name' => 'Holy See (Vatican City State)', 'iso_code' => 'VAT', 'country' => 'Holy See (Vatican City State)', 'is_default' => false],
            ['name' => 'Saint Vincent and the Grenadines', 'iso_code' => 'VCT', 'country' => 'Saint Vincent and the Grenadines', 'is_default' => false],
            ['name' => 'Venezuela, Bolivarian Republic of', 'iso_code' => 'VEN', 'country' => 'Venezuela, Bolivarian Republic of', 'is_default' => false],
            ['name' => 'Virgin Islands, British', 'iso_code' => 'VGB', 'country' => 'Virgin Islands, British', 'is_default' => false],
            ['name' => 'Virgin Islands, U.S.', 'iso_code' => 'VIR', 'country' => 'Virgin Islands, U.S.', 'is_default' => false],
            ['name' => 'Viet Nam', 'iso_code' => 'VNM', 'country' => 'Viet Nam', 'is_default' => false],
            ['name' => 'Vanuatu', 'iso_code' => 'VUT', 'country' => 'Vanuatu', 'is_default' => false],
            ['name' => 'Wallis and Futuna', 'iso_code' => 'WLF', 'country' => 'Wallis and Futuna', 'is_default' => false],
            ['name' => 'Samoa', 'iso_code' => 'WSM', 'country' => 'Samoa', 'is_default' => false],
            ['name' => 'Yemen', 'iso_code' => 'YEM', 'country' => 'Yemen', 'is_default' => false],
            ['name' => 'South Africa', 'iso_code' => 'ZAF', 'country' => 'South Africa', 'is_default' => false],
            ['name' => 'Zambia', 'iso_code' => 'ZMB', 'country' => 'Zambia', 'is_default' => false],
            ['name' => 'Zimbabwe', 'iso_code' => 'ZWE', 'country' => 'Zimbabwe', 'is_default' => false],
        ];

        foreach ($nationalities as $n) {
            $country = Country::where('name', $n['country'])->first();

            if ($country) {
                Nationality::updateOrCreate(
                    ['name' => $n['name']],
                    [
                        'iso_code' => $n['iso_code'],
                        'country_id' => $country->id,
                        'is_default' => $n['is_default']
                    ]
                );
            }
        }
    }
}
