<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\City;
use App\Models\Neighborhood;

class NeighborhoodsSeeder extends Seeder
{
    public function run(): void
    {
        $barrios = [
            ['name' => '12 de Octubre', 'city_name' => 'Bahía Blanca'],
            ['name' => '1º de Mayo', 'city_name' => 'Bahía Blanca'],
            ['name' => '27 de Junio (UPCN)', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Aldea Romana', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Altos de Bahía', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Altos de Palihue', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Anchorena', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Avellaneda', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Bahía Blanca', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrancas del Golf', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio 5 de Abril', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Bella Vista', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Ceferino Namuncurá', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Colón', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Comahue', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Cooperativa del Polo', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Coronel Estomba', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Eduardo Cenci', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Enrique Julio', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Hospital', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Juan Carlos Lobo', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Kilómetro 5', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio La Falda', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Los Álamos', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Maldonado', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Mara', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Moreno', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Napostá', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Oasis', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Obrero', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Pacífico', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Palos Verdes', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Parque Independencia', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Parque Norte', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Parque Palihue', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Parque Patagonia', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Parque Patagonia Norte', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Parque San Agustín', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Parque San Ignacio', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Parque del Sol', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Pedro Pico', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio San Francisco', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Sevilla', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Barrio Universitario', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Bosque Alto', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Bº Cooperación', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Chacras de Palihue', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Don Bosco', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Don Ramiro', 'city_name' => 'Bahía Blanca'],
            ['name' => 'El Maitén', 'city_name' => 'Bahía Blanca'],
            ['name' => 'El Nacional', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Federico Massot', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Fratercoop', 'city_name' => 'Bahía Blanca'],
            ['name' => 'General Daniel Cerri', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Ingeniero White', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Irupe', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Las Acacias', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Las Lomitas', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Latino', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Loma Paraguaya', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Los Almendros', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Los Chañares', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Los Horneros', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Los Horneros II', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Los Muñecos', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Mariano Moreno', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Milla Mapu', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Moresino', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Namuncurá', 'city_name' => 'Bahía Blanca'],
            ['name' => 'New Liverpool', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Noroeste', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Pampa Central', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Portal del Este', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Richieri', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Rosendo López', 'city_name' => 'Bahía Blanca'],
            ['name' => 'San Agustín', 'city_name' => 'Bahía Blanca'],
            ['name' => 'San Carlos', 'city_name' => 'Bahía Blanca'],
            ['name' => 'San Martín', 'city_name' => 'Bahía Blanca'],
            ['name' => 'San Miguel', 'city_name' => 'Bahía Blanca'],
            ['name' => 'San Roque', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Santa Margarita', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Sevilla', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Solares Norte', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Sánchez Elia', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Talleres', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Thompson', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Tiro Federal', 'city_name' => 'Bahía Blanca'],
            ['name' => 'UOM', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Viajantes del Sur', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Aeropuerto', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Amaducci', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Belgrano', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Bordeu', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Buenos Aires', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Cerrito', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Delfina', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Duprat', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Floresta', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Harding Green', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Italia', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Libre', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Loreto', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Mitre', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Muñiz', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Nocito', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Parodi', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Ressia', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Rosario', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Rosas', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Serra', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa Soldati', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Villa del Parque', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Vista Alegre', 'city_name' => 'Bahía Blanca'],
            ['name' => 'Agronomía', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Almagro', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Balvanera', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Barracas', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Belgrano', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Boedo', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Caballito', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Chacarita', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Coghlan', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Colegiales', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Constitución', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Flores', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Floresta', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'La Boca', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'La Paternal', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Liniers', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Mataderos', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Monserrat', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Monte Castro', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Nueva Pompeya', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Núñez', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Palermo', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Parque Avellaneda', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Parque Chacabuco', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Parque Patricios', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Puerto Madero', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Recoleta', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Retiro', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Saavedra', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'San Cristóbal', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'San Nicolás', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'San Telmo', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Vélez Sársfield', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Versalles', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Villa Crespo', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Villa del Parque', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Villa Devoto', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Villa General Mitre', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Villa Lugano', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Villa Luro', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Villa Ortúzar', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Villa Pueyrredón', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Villa Real', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Villa Riachuelo', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Villa Santa Rita', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Villa Soldati', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
            ['name' => 'Villa Urquiza', 'city_name' => 'Ciudad Autónoma de Buenos Aires'],
        ];

        foreach ($barrios as $item) {
            $city = City::where('name', $item['city_name'])->first();
            if ($city) {
                Neighborhood::updateOrCreate(
                    ['name' => $item['name'], 'city_id' => $city->id],
                    ['is_default' => false]
                );
            }
        }
    }
}
